<?php $globalPreferences = array (
  'logo' => '/admin-panel/assets/images/logos/de310512f7004b4643cae34b160a0098.jpeg',
  'logo_updated_by' => 57,
  'let_register_user' => '1',
  'let_register_user_updated_by' => 57,
  'recover_account' => '0',
  'recover_account_updated_by' => 1,
  'name_of_system' => 'Ajax-Panel',
  'name_of_system_updated_by' => 57,
  'tab_icon' => '/admin-panel/assets/images/tab_icons/df41301a77302322f9d492e92eadd3bd.jpeg',
  'tab_icon_updated_by' => 57,
  'priority_status_display' => '0',
  'priority_status_display_updated_by' => 1,
  'status_display_amount_criterion' => '1',
  'status_display_amount_criterion_updated_by' => 1,
  'terms_of_use_and_privacy_policy' => 
  array (
    'es' => 'prueba en español<br>',
    'en' => '<div style="text-align: center;"><b><font style="font-size: 14px;">prueba in gles gege</font></b></div>',
    'fr' => 'hihi',
  ),
  'terms_of_use_and_privacy_policy_updated_by' => 57,
  'chat_alert_sound' => '1',
  'chat_alert_sound_updated_by' => 57,
  'content_registration_email' => 'link',
  'content_registration_email_updated_by' => 57,
  'account_recovering_mechanism' => 'link',
  'account_recovering_mechanism_updated_by' => 57,
  'account_recovering_mechanism_automatic' => '0',
  'account_recovering_mechanism_automatic_updated_by' => 57,
  'apply_general_session_duration' => '1',
  'general_session_duration_amount_val' => '12',
  'general_session_duration_amount_type' => 'hours',
  'apply_default_config_inactivity_time_limit' => 'no',
  'default_config_inactivity_time_limit_amount_val' => '5',
  'default_config_inactivity_time_limit_amount_type' => 'minutes',
  'default_language_system' => 'en',
  'default_language_system_updated_by' => 57,
  'format_show_items' => 'pagination',
  'format_edit_items' => 'modal',
);?>