<?php
	$GLOBALS["ID_TO_CODE_BANKS"] = [
		'5' => 'bdv',
		'6' => 'banesco',
		'7' => 'bbva',
		'8' => 'mercantil',
		'9' => 'tesoro',
		'10' => 'bicentenario',
		'11' => 'bod',
		'12' => 'exterior',
		'13' => 'credito',
		'14' => 'caribe',
		'15' => 'bfc',
		'16' => 'bnc',
		'17' => 'bancrecer',
		'18' => 'banplus',
		'19' => 'plaza',
		'20' => 'caroni',
		'21' => '100banco',
		'22' => 'sofitasa',
		'23' => 'delsur',
		'24' => 'banfanb',
		'25' => 'mibanco',
		'26' => 'agricola',
		'27' => 'activo',
		'28' => 'citibank',
		'29' => 'bancoex',
		'30' => 'bancaamiga',
		'31' => 'bangente',
		'32' => 'novobanco',
		'34' => 'imcp',
		'35' => 'bec',
		'36' => 'bid',
	]
?>