<?php
	$GLOBALS["CODE_TO_ID_BANKS"] = [
		'bdv' => 5,
		'banesco' => 6,
		'bbva' => 7,
		'mercantil' => 8,
		'tesoro' => 9,
		'bicentenario' => 10,
		'bod' => 11,
		'exterior' => 12,
		'credito' => 13,
		'caribe' => 14,
		'bfc' => 15,
		'bnc' => 16,
		'bancrecer' => 17,
		'banplus' => 18,
		'plaza' => 19,
		'caroni' => 20,
		'100banco' => 21,
		'sofitasa' => 22,
		'delsur' => 23,
		'banfanb' => 24,
		'mibanco' => 25,
		'agricola' => 26,
		'activo' => 27,
		'citibank' => 28,
		'bancoex' => 29,
		'bancaamiga' => 30,
		'bangente' => 31,
		'novobanco' => 32,
		'imcp' => 34,
		'bec' => 35,
		'bid' => 36,
	]
?>