<?php

return [
    'defaults' => [
        'logo' => '/admin-panel/assets/images/logos/de310512f7004b4643cae34b160a0098.jpeg',
        'logo_updated_by' => 57,
        'let_register_user' => '1',
        'let_register_user_updated_by' => 57,
        'recover_account' => '0',
        'recover_account_updated_by' => 1,
        'name_of_system' => 'Admin-Panel',
        'name_of_system_updated_by' => 57,
        'tab_icon' => '/admin-panel/assets/images/tab_icons/df41301a77302322f9d492e92eadd3bd.jpeg',
        'tab_icon_updated_by' => 57,
        'priority_status_display' => '0',
        'priority_status_display_updated_by' => 1,
        'status_display_amount_criterion' => '1',
        'status_display_amount_criterion_updated_by' => 1,
        'terms_of_use_and_privacy_policy' => [
            'es' => '<div style="text-align: center;"><b>prueba en espaÃ±ol</b></div>',
            'en' => '<div style="text-align: center;"><b><font style="font-size: 14px;">english test</font></b></div>',
            'fr' => 'hihi',
        ],
        'terms_of_use_and_privacy_policy_updated_by' => 57,
        'chat_alert_sound' => '1',
        'chat_alert_sound_updated_by' => 57,
        'content_registration_email' => 'link',
        'content_registration_email_updated_by' => 57,
        'account_recovering_mechanism' => 'link',
        'account_recovering_mechanism_updated_by' => 57,
        'account_recovering_mechanism_automatic' => '1',
        'account_recovering_mechanism_automatic_updated_by' => 57,
        'apply_general_session_duration' => '1',
        'general_session_duration_amount_val' => '12',
        'general_session_duration_amount_type' => 'hours',
        'apply_default_config_inactivity_time_limit' => 'no',
        'default_config_inactivity_time_limit_amount_val' => '5',
        'default_config_inactivity_time_limit_amount_type' => 'minutes',
        'default_language_system' => 'en',
        'default_language_system_updated_by' => 57,
        'format_show_items' => 'pagination',
        'format_edit_items' => 'modal',
        'installed' => 1,
        'db_address' => 'db',
        'db_name' => 'admin_panel',
        'db_user' => 'app_adminpanel',
        'db_password' => 'NahrQ-3gFaBumSWr=jsKA!Bu',
        'smtp_host' => 'smtp.invalid',
        'smtp_port' => 587,
        'smtp_email_from' => 'no-reply@admin-panel.invalid',
        'smtp_password_from' => '*OSp=3WH5m5v#MVlTY*N',
        'smtp_fullname_from' => 'Admin Panel System',
        'smtp_secure' => false,
        'default_user_changed' => false,

        'path_cloud_route' => '/storage/admin-panel/cloud/',
        'path_tmp_files' => '/storage/admin-panel/tmp/',
        'path_terms_folder' => '/assets/js/__languages__/',
        'path_audio_notifications_folder' => '/assets/audio/notifications/',
    ],

    'keys' => [
        'name_of_system' => ['group' => 'app', 'env' => ['APP_NAME'], 'type' => 'string', 'mutable' => true],
        'default_language_system' => ['group' => 'app', 'env' => ['APP_LOCALE', 'AP_DEFAULT_LANGUAGE'], 'type' => 'string', 'mutable' => true],
        'installed' => ['group' => 'app', 'env' => ['AP_INSTALLED'], 'type' => 'int', 'mutable' => true],

        'db_address' => ['group' => 'db', 'env' => ['DB_HOST'], 'type' => 'string', 'mutable' => true],
        'db_name' => ['group' => 'db', 'env' => ['DB_DATABASE'], 'type' => 'string', 'mutable' => true],
        'db_user' => ['group' => 'db', 'env' => ['DB_USERNAME'], 'type' => 'string', 'mutable' => true],
        'db_password' => ['group' => 'db', 'env' => ['DB_PASSWORD'], 'type' => 'string', 'mutable' => true],

        'smtp_host' => ['group' => 'smtp', 'env' => ['MAIL_HOST'], 'type' => 'string', 'mutable' => true],
        'smtp_port' => ['group' => 'smtp', 'env' => ['MAIL_PORT'], 'type' => 'int', 'mutable' => true],
        'smtp_email_from' => ['group' => 'smtp', 'env' => ['MAIL_FROM_ADDRESS', 'MAIL_USERNAME'], 'type' => 'string', 'mutable' => true],
        'smtp_password_from' => ['group' => 'smtp', 'env' => ['MAIL_PASSWORD'], 'type' => 'string', 'mutable' => true],
        'smtp_fullname_from' => ['group' => 'smtp', 'env' => ['MAIL_FROM_NAME'], 'type' => 'string', 'mutable' => true],
        'smtp_secure' => ['group' => 'smtp', 'env' => ['AP_SMTP_SECURE', 'MAIL_ENCRYPTION'], 'type' => 'bool', 'mutable' => true],

        'path_cloud_route' => ['group' => 'paths', 'env' => ['AP_PATH_CLOUD_ROUTE'], 'type' => 'string', 'mutable' => true],
        'path_tmp_files' => ['group' => 'paths', 'env' => ['AP_PATH_TMP_FILES'], 'type' => 'string', 'mutable' => true],
        'path_terms_folder' => ['group' => 'paths', 'env' => ['AP_PATH_TERMS_FOLDER'], 'type' => 'string', 'mutable' => true],
        'path_audio_notifications_folder' => ['group' => 'paths', 'env' => ['AP_PATH_AUDIO_NOTIFICATIONS_FOLDER'], 'type' => 'string', 'mutable' => true],

        'let_register_user' => ['group' => 'feature_flags', 'env' => ['AP_FEATURE_LET_REGISTER_USER'], 'type' => 'string', 'mutable' => true],
        'recover_account' => ['group' => 'feature_flags', 'env' => ['AP_FEATURE_RECOVER_ACCOUNT'], 'type' => 'string', 'mutable' => true],
        'account_recovering_mechanism_automatic' => ['group' => 'feature_flags', 'env' => ['AP_FEATURE_ACCOUNT_RECOVERY_AUTOMATIC'], 'type' => 'string', 'mutable' => true],
        'apply_general_session_duration' => ['group' => 'feature_flags', 'env' => ['AP_FEATURE_APPLY_GENERAL_SESSION_DURATION'], 'type' => 'string', 'mutable' => true],
    ],

    'groups' => [
        'app' => ['name_of_system', 'default_language_system', 'installed'],
        'db' => ['db_address', 'db_name', 'db_user', 'db_password'],
        'smtp' => ['smtp_host', 'smtp_port', 'smtp_email_from', 'smtp_password_from', 'smtp_fullname_from', 'smtp_secure'],
        'paths' => ['path_cloud_route', 'path_tmp_files', 'path_terms_folder', 'path_audio_notifications_folder'],
        'feature_flags' => ['let_register_user', 'recover_account', 'account_recovering_mechanism_automatic', 'apply_general_session_duration'],
    ],

    'mutable_keys' => [
        'logo',
        'logo_updated_by',
        'let_register_user',
        'let_register_user_updated_by',
        'recover_account',
        'recover_account_updated_by',
        'name_of_system',
        'name_of_system_updated_by',
        'tab_icon',
        'tab_icon_updated_by',
        'priority_status_display',
        'priority_status_display_updated_by',
        'status_display_amount_criterion',
        'status_display_amount_criterion_updated_by',
        'terms_of_use_and_privacy_policy',
        'terms_of_use_and_privacy_policy_updated_by',
        'chat_alert_sound',
        'chat_alert_sound_updated_by',
        'content_registration_email',
        'content_registration_email_updated_by',
        'account_recovering_mechanism',
        'account_recovering_mechanism_updated_by',
        'account_recovering_mechanism_automatic',
        'account_recovering_mechanism_automatic_updated_by',
        'apply_general_session_duration',
        'general_session_duration_amount_val',
        'general_session_duration_amount_type',
        'apply_default_config_inactivity_time_limit',
        'default_config_inactivity_time_limit_amount_val',
        'default_config_inactivity_time_limit_amount_type',
        'default_language_system',
        'default_language_system_updated_by',
        'format_show_items',
        'format_edit_items',
        'installed',
        'db_address',
        'db_name',
        'db_user',
        'db_password',
        'smtp_host',
        'smtp_port',
        'smtp_email_from',
        'smtp_password_from',
        'smtp_fullname_from',
        'smtp_secure',
        'default_user_changed',
        'path_cloud_route',
        'path_tmp_files',
        'path_terms_folder',
        'path_audio_notifications_folder',
    ],

    'runtime_json_path' => __DIR__.'/../storage/admin-panel/runtime-settings.json',
    'legacy_snapshot_path' => __DIR__.'/../storage/admin-panel/legacy-settings.snapshot.php',
];
